const dummies = [
  {
    username: 'brian',
    password: 'mete0r',
    sessionId: 'hello1',
    wins: 3,
    losses: 7,
    balance: 100,
  },
  {
    username: 'kelly',
    password: 'mete0r',
    sessionId: 'hello2',
    wins: 7,
    losses: 3,
    balance: 100,
  },
  {
    username: 'sarah',
    password: 'mete0r',
    sessionId: 'hello3',
    wins: 0,
    losses: 0,
    balance: 100,
  },
  {
    username: 'cliff',
    password: 'mete0r',
    sessionId: 'hello4',
    wins: 3,
    losses: 7,
    balance: 100,
  },
  {
    username: 'max',
    password: 'mete0r',
    sessionId: 'hello5',
    wins: 10,
    losses: 10,
    balance: 100,
  },
  {
    username: 'hubert',
    password: 'mete0r',
    sessionId: 'hello6',
    wins: 10,
    losses: 10,
    balance: 100,
  },
  {
    username: 'dennis',
    password: 'mete0r',
    sessionId: 'hello40',
    wins: 3,
    losses: 99,
    balance: 100,
  },
  {
    username: 'abc',
    password: 'mete0r',
    sessionId: 'hello41',
    wins: 3,
    losses: 99,
    balance: 100,
  },
  {
    username: 'def',
    password: 'mete0r',
    sessionId: 'hello42',
    wins: 3,
    losses: 99,
    balance: 100,
  },
  {
    username: 'hij',
    password: 'mete0r',
    sessionId: 'hello43',
    wins: 3,
    losses: 99,
    balance: 100,
  },
];

module.exports = dummies;
